I wanted to find the reason that my GBR was underperforming the original paper's results. What I found was that they were likely using more inputs than implied.

In [5]:
import pandas as pd
import numpy as np
import re
pd.set_option('display.max_columns', 500)

housing_data = pd.read_csv('./Data/kc_house_data.csv')

no_price_cols = [i for i in housing_data.columns if i not in {'price', 'date', 'id'}]

X = housing_data[no_price_cols]
y = housing_data['price']
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [7]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
# from sklearn.experimental import enable_hist_gradient_boosting
# from sklearn.ensemble import HistGradientBoostingRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

tree_depth_options = [3,5,8,10]
estimator_options = [50, 100, 200, 300, 400, 500]

for max_depth in tree_depth_options:
    for estimators in estimator_options:
        print(f'Testing for estimators={estimators}, max_depth={max_depth}')

        gbr = GradientBoostingRegressor(
            max_depth=max_depth,
            learning_rate=0.1,
            n_estimators=estimators  # number of trees
        )

        gbr.fit(X_train, y_train)
        
        y_pred = gbr.predict(X_test)
        this_score = r2_score(y_test, y_pred)
        print(f"Test r2 score: {this_score:.02f}")

Testing for estimators=50, max_depth=3
Test r2 score: 0.84
Testing for estimators=100, max_depth=3
Test r2 score: 0.87
Testing for estimators=200, max_depth=3
Test r2 score: 0.88
Testing for estimators=300, max_depth=3
Test r2 score: 0.89
Testing for estimators=400, max_depth=3
Test r2 score: 0.89
Testing for estimators=500, max_depth=3
Test r2 score: 0.89
Testing for estimators=50, max_depth=5
Test r2 score: 0.89
Testing for estimators=100, max_depth=5
Test r2 score: 0.89
Testing for estimators=200, max_depth=5
Test r2 score: 0.90
Testing for estimators=300, max_depth=5
Test r2 score: 0.90
Testing for estimators=400, max_depth=5
Test r2 score: 0.90
Testing for estimators=500, max_depth=5
Test r2 score: 0.90
Testing for estimators=50, max_depth=8
Test r2 score: 0.90
Testing for estimators=100, max_depth=8
Test r2 score: 0.90
Testing for estimators=200, max_depth=8
Test r2 score: 0.90
Testing for estimators=300, max_depth=8
Test r2 score: 0.90
Testing for estimators=400, max_depth=8
Test r2 score: 0.90
Testing for estimators=500, max_depth=8
Test r2 score: 0.90
Testing for estimators=50, max_depth=10
Test r2 score: 0.89
Testing for estimators=100, max_depth=10
Test r2 score: 0.89
Testing for estimators=200, max_depth=10
Test r2 score: 0.89
Testing for estimators=300, max_depth=10
Test r2 score: 0.89
Testing for estimators=400, max_depth=10
Test r2 score: 0.89
Testing for estimators=500, max_depth=10
Test r2 score: 0.89